#include "update_screen.h"

#include <stdint.h>
#include <string.h>

#include "ili9341_driver.h"
#include "lvgl.h" /* only for the font's table types; LVGL itself isn't running */

/* update_font.c, generated by resources/generate_fonts.sh: DejaVu, ASCII only,
 * uncompressed (1 or 2 bits per pixel), one contiguous character range. */
extern const lv_font_t update_font;

/* RGB565: black, white, the UI's accent yellow (0xf3a51c), gray (0x888888). */
#define COLOR_BLACK  0x0000
#define COLOR_WHITE  0xFFFF
#define COLOR_ACCENT 0xF523
#define COLOR_GRAY   0x8C51

/* Layout, px: title, progress bar (200 wide with 20px margins, as the UI's
 * rows), status line. */
#define TITLE_Y  110
#define BAR_X    20
#define BAR_Y    140
#define BAR_W    200
#define BAR_H    20
#define BAR_EDGE 2 /* gap between the outline and the fill */
#define STATUS_Y 175

/* Widest glyph box of update_font, px, with margin. */
#define MAX_GLYPH_W 24

static int drawn_percent;

static const lv_font_fmt_txt_glyph_dsc_t *glyph(char c)
{
    const lv_font_fmt_txt_dsc_t *dsc = update_font.dsc;
    const lv_font_fmt_txt_cmap_t *cmap = &dsc->cmaps[0];
    uint32_t code = (unsigned char)c;
    if (code < cmap->range_start || code >= cmap->range_start + cmap->range_length) code = '?';
    return &dsc->glyph_dsc[code - cmap->range_start + cmap->glyph_id_start];
}

/* adv_w is in 1/16 px. */
static int advance(const lv_font_fmt_txt_glyph_dsc_t *g)
{
    return (g->adv_w + 8) >> 4;
}

static int text_width(const char *text)
{
    int width = 0;
    for (; *text; text++) width += advance(glyph(*text));
    return width;
}

/* `color` (RGB565) scaled by coverage / full. */
static uint16_t shade(uint16_t color, unsigned coverage, unsigned full)
{
    uint16_t r = ((color >> 11) & 0x1F) * coverage / full;
    uint16_t g = ((color >> 5) & 0x3F) * coverage / full;
    uint16_t b = (color & 0x1F) * coverage / full;
    return (r << 11) | (g << 5) | b;
}

/* On black: each pixel's coverage picks one of the shades of `color`. */
static void draw_glyph(const lv_font_fmt_txt_glyph_dsc_t *g, int x, int y, uint16_t color)
{
    const lv_font_fmt_txt_dsc_t *dsc = update_font.dsc;
    const unsigned bpp = dsc->bpp;
    const unsigned full = (1u << bpp) - 1;
    uint16_t shades[4];
    uint8_t row[2 * MAX_GLYPH_W];

    if (g->box_w == 0 || g->box_h == 0 || g->box_w > MAX_GLYPH_W || bpp > 2) return;
    for (unsigned i = 0; i <= full; i++) shades[i] = shade(color, i, full);

    int top = y + update_font.line_height - update_font.base_line - g->box_h - g->ofs_y;
    ili9341_begin_pixels(x + g->ofs_x, top, g->box_w, g->box_h);

    /* Pixels are packed MSB first, continuously across rows. */
    const uint8_t *bitmap = &dsc->glyph_bitmap[g->bitmap_index];
    uint32_t bit = 0;
    for (int py = 0; py < g->box_h; py++) {
        for (int px = 0; px < g->box_w; px++, bit += bpp) {
            unsigned coverage = (bitmap[bit >> 3] >> (8 - bpp - (bit & 7))) & full;
            row[2 * px] = shades[coverage] >> 8;
            row[2 * px + 1] = shades[coverage] & 0xFF;
        }
        ili9341_write_pixels(row, 2 * g->box_w);
    }
}

/* Clears the line and draws `text` centered on it. */
static void draw_centered(const char *text, int y, uint16_t color)
{
    ili9341_fill_rect(0, y, ILI9341_HOR_RES, update_font.line_height, COLOR_BLACK);
    int x = (ILI9341_HOR_RES - text_width(text)) / 2;
    for (; *text; text++) {
        const lv_font_fmt_txt_glyph_dsc_t *g = glyph(*text);
        draw_glyph(g, x, y, color);
        x += advance(g);
    }
}

void update_screen_init(void)
{
    ili9341_fill_rect(0, 0, ILI9341_HOR_RES, ILI9341_VER_RES, COLOR_BLACK);
    draw_centered("Updating firmware", TITLE_Y, COLOR_WHITE);

    ili9341_fill_rect(BAR_X, BAR_Y, BAR_W, 1, COLOR_GRAY);
    ili9341_fill_rect(BAR_X, BAR_Y + BAR_H - 1, BAR_W, 1, COLOR_GRAY);
    ili9341_fill_rect(BAR_X, BAR_Y, 1, BAR_H, COLOR_GRAY);
    ili9341_fill_rect(BAR_X + BAR_W - 1, BAR_Y, 1, BAR_H, COLOR_GRAY);
    drawn_percent = 0;
}

void update_screen_set_progress(int percent)
{
    const int inner_x = BAR_X + 1 + BAR_EDGE;
    const int inner_y = BAR_Y + 1 + BAR_EDGE;
    const int inner_w = BAR_W - 2 * (1 + BAR_EDGE);
    const int inner_h = BAR_H - 2 * (1 + BAR_EDGE);

    if (percent < 0) percent = 0;
    if (percent > 100) percent = 100;
    if (percent < drawn_percent) {
        ili9341_fill_rect(inner_x, inner_y, inner_w, inner_h, COLOR_BLACK);
        drawn_percent = 0;
    }

    /* Only the newly filled part. */
    int from = inner_w * drawn_percent / 100;
    int to = inner_w * percent / 100;
    if (to > from) ili9341_fill_rect(inner_x + from, inner_y, to - from, inner_h, COLOR_ACCENT);
    drawn_percent = percent;
}

void update_screen_set_status(const char *status)
{
    draw_centered(status, STATUS_Y, COLOR_ACCENT);
}
